sudo: required

language: python

python:
- "2.6"
- "2.7"
- "3.4"
- "3.5"
- "3.6"

services:
- docker

env:
  global:
  - SMB_USER: smbuser
  - SMB_PASSWORD: smbpassword
  - SMB_SERVER: 127.0.0.1
  - SMB_SHARE: share

install:
- export SMB_PORT=$(ndd /dev/tcp tcp_smallest_anon_port)
- docker run -d -p $SMB_PORT:445 -v $(pwd):/app -w /app -e SMB_USER=$SMB_USER -e SMB_PASSWORD=$SMB_PASSWORD -e SMB_SHARE=$SMB_SHARE centos:7 /bin/bash /app/build-scripts/setup_samba.sh
- pip install -U pip setuptools
- pip install .
- pip install -r requirements-test.txt
- pip install python-coveralls

script:
- py.test -v --pep8 --cov smbprotocol --cov-report term-missing

after_success:
- coveralls
