sudo: required

language: python

python:
- "2.6"
- "2.7"
- "3.4"
- "3.5"
- "3.6"

services:
- docker

env:
  global:
  - SMB_USER: smbuser
  - SMB_PASSWORD: smbpassword
  - SMB_SERVER: 127.0.0.1
  - SMB_SHARE: share
  - SMB_PORT: 445

install:
- |
  if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then
      export SMB_SKIP="True";
  else
      docker run -d -p $SMB_PORT:445 -v $(pwd)/build-scripts:/app -w /app -e SMB_USER=$SMB_USER -e SMB_PASSWORD=$SMB_PASSWORD -e SMB_SHARE=$SMB_SHARE centos:7 /bin/bash /app/setup_samba.sh
  fi
- pip install -U pip setuptools
- pip install .
- pip install -r requirements-test.txt
- pip install python-coveralls

script:
- py.test -v --instafail --pep8 --cov smbprotocol --cov-report term-missing

after_success:
- coveralls
