sudo: required

language: python

python:
- 2.6
- 2.7
- 3.4
- 3.5
- 3.6

# Python 3.7 requires 16.04 (Xenial), this is a hack to get that specific
# distro running that version until I can swap the rest over officially
matrix:
  include:
  - python: 3.7
    dist: xenial

services:
- docker

env:
  global:
  - SMB_USER: smbuser
  - SMB_PASSWORD: smbpassword
  - SMB_SERVER: 127.0.0.1
  - SMB_SHARE: share
  - SMB_PORT: 445

install:
- docker run -d -p $SMB_PORT:445 -v $(pwd)/build-scripts:/app -w /app -e SMB_USER=$SMB_USER -e SMB_PASSWORD=$SMB_PASSWORD -e SMB_SHARE=$SMB_SHARE centos:7 /bin/bash /app/setup_samba.sh;
- pip install --upgrade pip setuptools
- pip install .
- pip install -r requirements-test.txt
- pip install coveralls
# make sure the Samba service on the container is up and running
- python ./build-scripts/check_samba.py

script:
- py.test -v --instafail --pep8 --cov smbprotocol --cov-report term-missing

after_success:
- coveralls
